apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cert-manager
# patches:
#   - patch: |-
#       - op: replace
#         path: /spec/chart/spec/version
#         value: "x.y.z"
#     target:
#       kind: HelmRelease
#       name: cert-manager
