apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/traefik
# patches:
#   - patch: |-
#       - op: replace
#         patch: /spec/chart/spec/version
#         value "x.y.z."
